# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_attach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attach',
            name='post',
        ),
        migrations.DeleteModel(
            name='Attach',
        ),
    ]
