# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160126_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='coverfile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
